title: Khu Key board
description: 경희대학교 전자공학과 Khu Key board 입니다.
show_downloads: false

baseurl: "/" # change this to the subpath of your site, e.g. /blog. Leave it empty if you don't need it.
url: "https://khukeyboard.github.io" # change this to the base hostname & protocol for your site

cayman-blog:
   date_format: "%b %-d, %Y"

theme: # leave it empty

# social
   author: "sauber92"
   image: /thumbnail.png
